CREATE TABLE majors (
	major_name VARCHAR(100),
	major_id INT Generated by default as IDENTITY PRIMARY KEY,
	department_id int,
	FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

INSERT INTO MAJORS (major_id,major_name, department_id) values (1,'Software Engineering',2);
INSERT INTO MAJORS (major_id,major_name, department_id) values (2,'Data Science',2);
INSERT INTO MAJORS (major_id,major_name, department_id) values (3,'Artificial Intelligence',2);
INSERT INTO MAJORS (major_id,major_name, department_id) values (4,'Applied Mathematics',3);
INSERT INTO MAJORS (major_id,major_name, department_id) values (5,'Statistics',4);
INSERT INTO MAJORS (major_id,major_name, department_id) values (6,'Astrophysics',4);
INSERT INTO MAJORS (major_id,major_name, department_id) values (7,'Quantum Mechanics',5);
INSERT INTO MAJORS (major_id,major_name, department_id) values (8,'Genetics',5);
INSERT INTO MAJORS (major_id,major_name, department_id) values (9,'Microbiology',5);
SELECT * from majors;

CREATE TABLE departments (
	department_id int generated by default as IDENTITY,
	department_name VARCHAR(100)
)
INSERT INTO departments values (2,'Computer Science')
INSERT INTO departments values (3,'Mathematics')
INSERT INTO departments values (4,'Physics');
INSERT INTO departments values (5,'Biology')
SELECT * from departments;

SELECT * from courses;

INSERT INTO STUDENTS values (1,'John Doe','john.doe@student.com', 20, 1);
INSERT INTO STUDENTS values (2,'Jane Doe','jane.doe@student.com', 21, 2);
INSERT INTO STUDENTS values (3,'Sam Smith','sam.smith@student.com', 22, 3);
INSERT INTO STUDENTS values (4,'Lucy Brown','lucy.brown@student.com', 19, 4);
INSERT INTO STUDENTS values (5,'Mike Green','mike.green@student.com', 20, 8);

INSERT INTO professors values (101, 'Dr. Alice Smith', 'alice.smith@university.com', 2);
INSERT INTO professors values (102, 'Dr. Bob Johnson', 'bob.johnson@university.com', 3);
INSERT INTO professors values (103, 'Dr. Carol Lee', 'carol.lee@university.com', 4);
INSERT INTO professors values (104, 'Dr. David Brown', 'david.brown@university.com', 5);
INSERT INTO professors values (105, 'Dr. Eva Green', 'eva.green@university.com', 2);
SELECT * from professors;



SELECT * from courses;
INSERT INTO courses values ('Introduction to Programming', 1001, 3,2);
INSERT INTO courses values ('Data Structures', 1002, 4,2);
INSERT INTO courses values ('Linear Algebra', 1003, 3,3);
INSERT INTO courses values ('Quantum Mechanics Basics', 1004, 4,4);
INSERT INTO courses values ('Molecular Biology', 1005, 3,5);


SELECT * FROM enrollments;
INSERT INTO enrollments values (1, 1, 1001, 'A');
INSERT INTO enrollments values (2, 1, 1002, 'B');
INSERT INTO enrollments values (3, 2, 1003, 'A');
INSERT INTO enrollments values (4, 3, 1004, 'C');
INSERT INTO enrollments values (5, 4, 1001, 'B');
INSERT INTO enrollments values (6, 5, 1005, 'A');

SELECT * from department_head;
INSERT INTO department_head values(101,2);
INSERT INTO department_head values(102,3);
INSERT INTO department_head values(103,4);
INSERT INTO department_head values(104,5);